name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 触发条件：当有推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # 使用 Node.js 版本 18，根据需要调整

    - name: Install dependencies
      run: npm ci # 或者使用 yarn install 如果你用的是 Yarn

    - name: Build the project
      run: npm run build # 确保这个命令会生成到 dist 目录

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTION_SECRET }}
        publish_dir: ./docs-dist # 构建产物所在的目录
        publish_branch: gh-pages # 发布分支
